export const LOAD_CAMPAIGNS_REQUEST = 'LOAD_CAMPAIGNS_REQUEST'
export const LOAD_CAMPAIGNS_SUCCESS = 'LOAD_CAMPAIGNS_SUCCESS'
export const LOAD_CAMPAIGNS_FAILURE = 'LOAD_CAMPAIGNS_FAILURE'

export const LOAD_CAMPAIGN_REQUEST = 'LOAD_CAMPAIGN_REQUEST'
export const LOAD_CAMPAIGN_SUCCESS = 'LOAD_CAMPAIGN_SUCCESS'
export const LOAD_CAMPAIGN_FAILURE = 'LOAD_CAMPAIGN_FAILURE'